FROM node:22-slim AS builder
WORKDIR /workspace

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

FROM node:22-slim AS runtime
WORKDIR /app

COPY package*.json ./
RUN npm install --production

COPY --from=builder /workspace/dist ./dist

ENV PORT=8080
EXPOSE 8080
CMD ["node", "dist/server/server.js"]
