/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWorkspaceRouteImport } from './routes/_authenticated/workspace'
import { Route as AuthenticatedSwapsRouteImport } from './routes/_authenticated/swaps'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedShiftsRouteImport } from './routes/_authenticated/shifts'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRosterRouteImport } from './routes/_authenticated/roster'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedMyRosterRouteImport } from './routes/_authenticated/my-roster'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedLeavesRouteImport } from './routes/_authenticated/leaves'
import { Route as AuthenticatedHolidaysRouteImport } from './routes/_authenticated/holidays'
import { Route as AuthenticatedHelpCenterRouteImport } from './routes/_authenticated/help-center'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedCalculatorRouteImport } from './routes/_authenticated/calculator'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance'
import { Route as AuthenticatedApplyLeaveRouteImport } from './routes/_authenticated/apply-leave'
import { Route as AuthenticatedRosterTemplatesRouteImport } from './routes/_authenticated/roster.templates'
import { Route as AuthenticatedRosterCreateRouteImport } from './routes/_authenticated/roster.create'
import { Route as AuthenticatedNotificationsIdRouteImport } from './routes/_authenticated/notifications.$id'
import { Route as AuthenticatedRosterViewIdRouteImport } from './routes/_authenticated/roster.view.$id'
import { Route as AuthenticatedRosterEditIdRouteImport } from './routes/_authenticated/roster.edit.$id'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkspaceRoute = AuthenticatedWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSwapsRoute = AuthenticatedSwapsRouteImport.update({
  id: '/swaps',
  path: '/swaps',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShiftsRoute = AuthenticatedShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRosterRoute = AuthenticatedRosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyRosterRoute = AuthenticatedMyRosterRouteImport.update({
  id: '/my-roster',
  path: '/my-roster',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeavesRoute = AuthenticatedLeavesRouteImport.update({
  id: '/leaves',
  path: '/leaves',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHolidaysRoute = AuthenticatedHolidaysRouteImport.update({
  id: '/holidays',
  path: '/holidays',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHelpCenterRoute = AuthenticatedHelpCenterRouteImport.update({
  id: '/help-center',
  path: '/help-center',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalculatorRoute = AuthenticatedCalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApplyLeaveRoute = AuthenticatedApplyLeaveRouteImport.update({
  id: '/apply-leave',
  path: '/apply-leave',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRosterTemplatesRoute =
  AuthenticatedRosterTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthenticatedRosterRoute,
  } as any)
const AuthenticatedRosterCreateRoute =
  AuthenticatedRosterCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedRosterRoute,
  } as any)
const AuthenticatedNotificationsIdRoute =
  AuthenticatedNotificationsIdRouteImport.update({
    id: '/notifications/$id',
    path: '/notifications/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRosterViewIdRoute =
  AuthenticatedRosterViewIdRouteImport.update({
    id: '/view/$id',
    path: '/view/$id',
    getParentRoute: () => AuthenticatedRosterRoute,
  } as any)
const AuthenticatedRosterEditIdRoute =
  AuthenticatedRosterEditIdRouteImport.update({
    id: '/edit/$id',
    path: '/edit/$id',
    getParentRoute: () => AuthenticatedRosterRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/support': typeof SupportRoute
  '/apply-leave': typeof AuthenticatedApplyLeaveRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/calculator': typeof AuthenticatedCalculatorRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/help-center': typeof AuthenticatedHelpCenterRoute
  '/holidays': typeof AuthenticatedHolidaysRoute
  '/leaves': typeof AuthenticatedLeavesRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/my-roster': typeof AuthenticatedMyRosterRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/roster': typeof AuthenticatedRosterRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/shifts': typeof AuthenticatedShiftsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/swaps': typeof AuthenticatedSwapsRoute
  '/workspace': typeof AuthenticatedWorkspaceRoute
  '/notifications/$id': typeof AuthenticatedNotificationsIdRoute
  '/roster/create': typeof AuthenticatedRosterCreateRoute
  '/roster/templates': typeof AuthenticatedRosterTemplatesRoute
  '/roster/edit/$id': typeof AuthenticatedRosterEditIdRoute
  '/roster/view/$id': typeof AuthenticatedRosterViewIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/support': typeof SupportRoute
  '/apply-leave': typeof AuthenticatedApplyLeaveRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/calculator': typeof AuthenticatedCalculatorRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/help-center': typeof AuthenticatedHelpCenterRoute
  '/holidays': typeof AuthenticatedHolidaysRoute
  '/leaves': typeof AuthenticatedLeavesRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/my-roster': typeof AuthenticatedMyRosterRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/roster': typeof AuthenticatedRosterRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/shifts': typeof AuthenticatedShiftsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/swaps': typeof AuthenticatedSwapsRoute
  '/workspace': typeof AuthenticatedWorkspaceRoute
  '/notifications/$id': typeof AuthenticatedNotificationsIdRoute
  '/roster/create': typeof AuthenticatedRosterCreateRoute
  '/roster/templates': typeof AuthenticatedRosterTemplatesRoute
  '/roster/edit/$id': typeof AuthenticatedRosterEditIdRoute
  '/roster/view/$id': typeof AuthenticatedRosterViewIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/support': typeof SupportRoute
  '/_authenticated/apply-leave': typeof AuthenticatedApplyLeaveRoute
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/calculator': typeof AuthenticatedCalculatorRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/help-center': typeof AuthenticatedHelpCenterRoute
  '/_authenticated/holidays': typeof AuthenticatedHolidaysRoute
  '/_authenticated/leaves': typeof AuthenticatedLeavesRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/my-roster': typeof AuthenticatedMyRosterRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/roster': typeof AuthenticatedRosterRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/shifts': typeof AuthenticatedShiftsRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRoute
  '/_authenticated/swaps': typeof AuthenticatedSwapsRoute
  '/_authenticated/workspace': typeof AuthenticatedWorkspaceRoute
  '/_authenticated/notifications/$id': typeof AuthenticatedNotificationsIdRoute
  '/_authenticated/roster/create': typeof AuthenticatedRosterCreateRoute
  '/_authenticated/roster/templates': typeof AuthenticatedRosterTemplatesRoute
  '/_authenticated/roster/edit/$id': typeof AuthenticatedRosterEditIdRoute
  '/_authenticated/roster/view/$id': typeof AuthenticatedRosterViewIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/pricing'
    | '/support'
    | '/apply-leave'
    | '/attendance'
    | '/billing'
    | '/calculator'
    | '/calendar'
    | '/dashboard'
    | '/help-center'
    | '/holidays'
    | '/leaves'
    | '/messages'
    | '/my-roster'
    | '/onboarding'
    | '/profile'
    | '/reports'
    | '/roster'
    | '/settings'
    | '/shifts'
    | '/staff'
    | '/swaps'
    | '/workspace'
    | '/notifications/$id'
    | '/roster/create'
    | '/roster/templates'
    | '/roster/edit/$id'
    | '/roster/view/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/pricing'
    | '/support'
    | '/apply-leave'
    | '/attendance'
    | '/billing'
    | '/calculator'
    | '/calendar'
    | '/dashboard'
    | '/help-center'
    | '/holidays'
    | '/leaves'
    | '/messages'
    | '/my-roster'
    | '/onboarding'
    | '/profile'
    | '/reports'
    | '/roster'
    | '/settings'
    | '/shifts'
    | '/staff'
    | '/swaps'
    | '/workspace'
    | '/notifications/$id'
    | '/roster/create'
    | '/roster/templates'
    | '/roster/edit/$id'
    | '/roster/view/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/pricing'
    | '/support'
    | '/_authenticated/apply-leave'
    | '/_authenticated/attendance'
    | '/_authenticated/billing'
    | '/_authenticated/calculator'
    | '/_authenticated/calendar'
    | '/_authenticated/dashboard'
    | '/_authenticated/help-center'
    | '/_authenticated/holidays'
    | '/_authenticated/leaves'
    | '/_authenticated/messages'
    | '/_authenticated/my-roster'
    | '/_authenticated/onboarding'
    | '/_authenticated/profile'
    | '/_authenticated/reports'
    | '/_authenticated/roster'
    | '/_authenticated/settings'
    | '/_authenticated/shifts'
    | '/_authenticated/staff'
    | '/_authenticated/swaps'
    | '/_authenticated/workspace'
    | '/_authenticated/notifications/$id'
    | '/_authenticated/roster/create'
    | '/_authenticated/roster/templates'
    | '/_authenticated/roster/edit/$id'
    | '/_authenticated/roster/view/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PricingRoute: typeof PricingRoute
  SupportRoute: typeof SupportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workspace': {
      id: '/_authenticated/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AuthenticatedWorkspaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/swaps': {
      id: '/_authenticated/swaps'
      path: '/swaps'
      fullPath: '/swaps'
      preLoaderRoute: typeof AuthenticatedSwapsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shifts': {
      id: '/_authenticated/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof AuthenticatedShiftsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roster': {
      id: '/_authenticated/roster'
      path: '/roster'
      fullPath: '/roster'
      preLoaderRoute: typeof AuthenticatedRosterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-roster': {
      id: '/_authenticated/my-roster'
      path: '/my-roster'
      fullPath: '/my-roster'
      preLoaderRoute: typeof AuthenticatedMyRosterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaves': {
      id: '/_authenticated/leaves'
      path: '/leaves'
      fullPath: '/leaves'
      preLoaderRoute: typeof AuthenticatedLeavesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/holidays': {
      id: '/_authenticated/holidays'
      path: '/holidays'
      fullPath: '/holidays'
      preLoaderRoute: typeof AuthenticatedHolidaysRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center': {
      id: '/_authenticated/help-center'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calculator': {
      id: '/_authenticated/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof AuthenticatedCalculatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apply-leave': {
      id: '/_authenticated/apply-leave'
      path: '/apply-leave'
      fullPath: '/apply-leave'
      preLoaderRoute: typeof AuthenticatedApplyLeaveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roster/templates': {
      id: '/_authenticated/roster/templates'
      path: '/templates'
      fullPath: '/roster/templates'
      preLoaderRoute: typeof AuthenticatedRosterTemplatesRouteImport
      parentRoute: typeof AuthenticatedRosterRoute
    }
    '/_authenticated/roster/create': {
      id: '/_authenticated/roster/create'
      path: '/create'
      fullPath: '/roster/create'
      preLoaderRoute: typeof AuthenticatedRosterCreateRouteImport
      parentRoute: typeof AuthenticatedRosterRoute
    }
    '/_authenticated/notifications/$id': {
      id: '/_authenticated/notifications/$id'
      path: '/notifications/$id'
      fullPath: '/notifications/$id'
      preLoaderRoute: typeof AuthenticatedNotificationsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roster/view/$id': {
      id: '/_authenticated/roster/view/$id'
      path: '/view/$id'
      fullPath: '/roster/view/$id'
      preLoaderRoute: typeof AuthenticatedRosterViewIdRouteImport
      parentRoute: typeof AuthenticatedRosterRoute
    }
    '/_authenticated/roster/edit/$id': {
      id: '/_authenticated/roster/edit/$id'
      path: '/edit/$id'
      fullPath: '/roster/edit/$id'
      preLoaderRoute: typeof AuthenticatedRosterEditIdRouteImport
      parentRoute: typeof AuthenticatedRosterRoute
    }
  }
}

interface AuthenticatedRosterRouteChildren {
  AuthenticatedRosterCreateRoute: typeof AuthenticatedRosterCreateRoute
  AuthenticatedRosterTemplatesRoute: typeof AuthenticatedRosterTemplatesRoute
  AuthenticatedRosterEditIdRoute: typeof AuthenticatedRosterEditIdRoute
  AuthenticatedRosterViewIdRoute: typeof AuthenticatedRosterViewIdRoute
}

const AuthenticatedRosterRouteChildren: AuthenticatedRosterRouteChildren = {
  AuthenticatedRosterCreateRoute: AuthenticatedRosterCreateRoute,
  AuthenticatedRosterTemplatesRoute: AuthenticatedRosterTemplatesRoute,
  AuthenticatedRosterEditIdRoute: AuthenticatedRosterEditIdRoute,
  AuthenticatedRosterViewIdRoute: AuthenticatedRosterViewIdRoute,
}

const AuthenticatedRosterRouteWithChildren =
  AuthenticatedRosterRoute._addFileChildren(AuthenticatedRosterRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApplyLeaveRoute: typeof AuthenticatedApplyLeaveRoute
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedCalculatorRoute: typeof AuthenticatedCalculatorRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHelpCenterRoute: typeof AuthenticatedHelpCenterRoute
  AuthenticatedHolidaysRoute: typeof AuthenticatedHolidaysRoute
  AuthenticatedLeavesRoute: typeof AuthenticatedLeavesRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedMyRosterRoute: typeof AuthenticatedMyRosterRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedRosterRoute: typeof AuthenticatedRosterRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedShiftsRoute: typeof AuthenticatedShiftsRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRoute
  AuthenticatedSwapsRoute: typeof AuthenticatedSwapsRoute
  AuthenticatedWorkspaceRoute: typeof AuthenticatedWorkspaceRoute
  AuthenticatedNotificationsIdRoute: typeof AuthenticatedNotificationsIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApplyLeaveRoute: AuthenticatedApplyLeaveRoute,
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedCalculatorRoute: AuthenticatedCalculatorRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHelpCenterRoute: AuthenticatedHelpCenterRoute,
  AuthenticatedHolidaysRoute: AuthenticatedHolidaysRoute,
  AuthenticatedLeavesRoute: AuthenticatedLeavesRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedMyRosterRoute: AuthenticatedMyRosterRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedRosterRoute: AuthenticatedRosterRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedShiftsRoute: AuthenticatedShiftsRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRoute,
  AuthenticatedSwapsRoute: AuthenticatedSwapsRoute,
  AuthenticatedWorkspaceRoute: AuthenticatedWorkspaceRoute,
  AuthenticatedNotificationsIdRoute: AuthenticatedNotificationsIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PricingRoute: PricingRoute,
  SupportRoute: SupportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
